SHELL=/bin/sh


read:
	@echo http://re.dopo.st/201015204327/ Ivan Nemytchenko ()

# =====================
all :
	@echo no\
		space
	@echo no\
	space
	@echo - one \
		space
	@echo one\
		Гибралтар

info:
	# 16.2 Utilities in Makefiles GNU make | book p. 158
	@echo = Utilities in Makefile = 
	@echo 
	@echo - awk cat cmp cp diff echo egrep expr false grep install-info ln ls
	@echo - mkdir mv printf pwd rm rmdir sed sleep sort tar test touch tr true